"""empty message

Revision ID: a3ec234f219c
Revises: 
Create Date: 2022-01-15 20:32:40.555189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ec234f219c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drinker',
    sa.Column('drinker_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('drinker_id')
    )
    op.create_table('the_drink',
    sa.Column('drink_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('distillery', sa.String(length=64), nullable=True),
    sa.Column('edition', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('nose', sa.String(length=32), nullable=True),
    sa.Column('palate', sa.String(length=32), nullable=True),
    sa.Column('finish', sa.String(length=32), nullable=True),
    sa.Column('person', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person'], ['drinker.drinker_id'], ),
    sa.PrimaryKeyConstraint('drink_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('the_drink')
    op.drop_table('drinker')
    # ### end Alembic commands ###
